# Generated by Django 4.1.4 on 2023-08-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(upload_to='boards/board_images/'),
        ),
    ]
