# Generated by Django 4.1.4 on 2023-08-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_boardbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
